services:
  node:
    container_name: budget_node
    build: app 
    networks:
      - frontend                                # Seperate NGINX and MYSQL network so
      - backend                                 # Only Node may communicate with both.
    volumes:
      - ./app/src:/usr/src/app/src
      - ./app/public:/usr/src/app/public
    depends_on:
      - budget_db

  budget_db:
    image: mysql:8.0
    container_name: budget_db
    ports:
      - 3308:3306                               # DEVELOPMENT ONLY
    environment:
      MYSQL_ROOT_PASSWORD: DEVELOPMENT          # DEVELOPMENT ONLY
      MYSQL_DATABASE: budget_tracker 
    networks:
      - backend 
    volumes:
      - budget_db:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"                             # PORT 3000 is only for dev
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html
    depends_on:
      - node
    restart: always
    networks:
      - frontend
volumes:
  budget_db:
networks:
  frontend:
  backend:
    external: false 
