version: '3.1'
services:
  node:
    container_name: budget_node
    build: app 
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend
    volumes:
      - ./app/src:/usr/src/app/src
      - ./app/public:/usr/src/app/public
  budget_db:
    image: mysql:8.0
    container_name: budget_db
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: DEVELOPMENT
      MYSQL_DATABASE: budget_tracker 
    networks:
      - backend 
    volumes:
      - budget_db:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always
volumes:
  budget_db:
networks:
  frontend:
  backend:
